services:
  pinact:
    profiles: ["cli"]
    build:
      dockerfile_inline: |
        FROM golang:1.25.4-alpine3.22

        RUN go install github.com/suzuki-shunsuke/pinact/cmd/pinact@latest
    working_dir: /var/app
    entrypoint: pinact
    volumes:
      - ./:/var/app
